### PR TITLE
[Elixir] Update maintainers.md

### PR DESCRIPTION
**Pull request by nathanchere**
As requested in #52 

I have excluded rubysolo, parkerl as they are flagged to not show on the web site. If this is incorrect and they should be included please let me know.

### CODE REVIEW

**Comment by neenjaw** [comment]
I think it's fine to not include them as I haven't seen a commit/issue form them in elixir for a long time.  Maybe just make sure, @ErikSchierboom can confirm their 'active-ness'?

**Comment by ErikSchierboom** [comment]
@neenjaw Not much more that I can do. I'd only list maintainers here that you are sure are active.

**Comment by iHiD** [comment]
Yeah. Only list people who have responded on the track issue to say they're getting involved. To the point where I'd just get those people to PR themselves. If they don't find the file then they're probably not taking an active interesting in v3.

**Comment by chriseyre2000** [comment]
- Christopher Eyre (Slack: @chriseyre2000, GitHub: [chriseyre2000] (https://github.com/chriseyre2000)

**Comment by devonestes** [comment]
I resolved the conflict, so this is good to go for now.

**Comment by neenjaw** [comment]
Lets merge this as the repo is quite chaotic right now, then we'll add fireproof socks when we have his info.

**Pull request merged**
