### PR TITLE
[All] Move practice exercises inside "exercises" key in config.json

### PR DESCRIPTION
**Pull request by ErikSchierboom**
When I imported the practice exercises a while back, I mistakenly added them at the root. They should be placed inside the `exercises` key, which this PR fixes.

### CODE REVIEW

**Review by neenjaw — APPROVED** [review]

**Review by verdammelt — APPROVED** [review]
common-lisp looks OK.

**Review by mirkoperillo — APPROVED** [review]

**Review by coriolinus — APPROVED** [review]
Confirmed with these steps

```sh
git checkout master && git pull
jq .practice languages/rust/config.json > master_practice.json
gh pr checkout 2718
jq .exercises.practice languages/rust/config.json > 2718_practice.json
diff master_practice.json 2718_practice.json
```

As expected, the diff was empty.

**Review by devkabiir — APPROVED** [review]

**Review by ee7 — APPROVED** [review]
Reviewed Nim only.

I manually made the same change that this PR claims to, and I confirm that the diff contains only the following:

```diff
$ diff pr2718-nim-config.json my-nim-config.json
244,250c244
<         "topics": [
<           "arrays",
<           "exception_handling",
<           "games",
<           "logic",
<           "matrices"
<         ],
---
>         "topics": ["arrays", "exception_handling", "games", "logic", "matrices"],
299,304c293
<         "topics": [
<           "cryptography",
<           "strings",
<           "text_formatting",
<           "transforming"
<         ],
---
>         "topics": ["cryptography", "strings", "text_formatting", "transforming"],
```

That is, it looks like this PR includes an unrelated change that splits long `topics` lines, but otherwise the diff is as expected.

**Review by SaschaMann — APPROVED** [review]

**Review by cmccandless — APPROVED** [review]

**Review by wneumann — APPROVED** [review]
Swift look right

**Review by ceddlyburge — APPROVED** [review]

**Review by NobbZ — APPROVED** [review]
On behalf of the erlang team

**Comment by ErikSchierboom** [comment]
Thanks everyone!

**Pull request merged**
