### PR TITLE
[CI] Add workflow to make prevent work-in-progress PRs from being merged

### PR DESCRIPTION
**Pull request by ErikSchierboom**
This PR adds a workflow that will have a non-zero exit code if the word WIP is found in the title. We can discuss here what the actual rule should be (if it should start with "WIP", if it should be "[WIP]", or whatever.

@SaschaMann I've requested you as a reviewed as I seem to recall you having some experience with GH actions.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
Oh this is hilarious. The PR can't be merged because it has WIP in its title :D

**Comment by SaschaMann** [comment]
At least we know that it works then! :D 

---

It seems to attach the new build instead of rerunning the previous one. That might cause issues if we require all checks to pass:

grafik

**Comment by SaschaMann** [comment]
Hm maybe failing the build to block it is not the way to do it anyway because it sends a notification to everyone with access to the repo.

**Comment by ErikSchierboom** [comment]
I'll look into the check run!

**Comment by ErikSchierboom** [comment]
@SaschaMann @iHiD The WIP app people have also created a GitHub action (which [source is very simple](https://github.com/wip/action/blob/master/index.js)). It does seem to work very nice!

**Comment by SaschaMann** [comment]
@ErikSchierboom It seems to be a container-action for some reason, so it'll be slow but perhaps you could just copy the `index.js` (and licence info) into the workflow?

**Comment by ErikSchierboom** [comment]
@SaschaMann It's not actually that slow I feel, just 10 seconds or so. To me that's not an issue. Do you feel like it is?

I'd prefer not to copy-paste source code if we can point to an existing action. @iHiD what do you think?

**Comment by SaschaMann** [comment]
Building the container takes 20s and the start up time for container actions tends to be high too. I'd guess natively it'd take 2-3s at most.

**Comment by SaschaMann** [comment]
It's not an issue workflow-wise, i.e. it won't block anyone. But I'd rather avoid wasting the resources if all it takes is copying the script or forking the action to turn it into a non-container action.

**Comment by SaschaMann** [comment]
I ported the script to run with github-script, takes 3s in total: #669 

IMO the savings justify copying the code.

**Comment by ErikSchierboom** [comment]
Superseded by #669.

**Comment by iHiD** [comment]
Thank you both :)

**Pull request closed without merging**
