### PR TITLE
[C#] Add headings to introductions

### PR DESCRIPTION
**Pull request by ErikSchierboom**
See #2293

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@mikedamay This is an initial attempt to add the concept-specific headings to the `introduction.md` files, as described in #2293. For most of the files, this was relatively easy. I've added some TODOs when I wasn't able to easily add the headings in a nice way. Would you be willing to go over the TODOs and fix those up?

**Comment by mikedamay** [comment]
logs-logs-logs introduces pattern-matching-constants concept. The heading has been removed from introduction.md. See issue #2719 for other required actions.

**Comment by mikedamay** [comment]
logs-logs-logs introduces accessibility concept. The heading has been removed from introduction.md. See issue #2720 for other required actions.

**Comment by mikedamay** [comment]
The weather-in-deather (what!) introduces that conditional-ternary concept.

**Review by mikedamay — APPROVED** [review]

**Comment by mikedamay** [comment]
All TODOs have been addressed except flag-enums which needs a wider consideration and change.

**Comment by ErikSchierboom** [comment]
Brilliant. Thanks @mikedamay!

**Pull request merged**
