### PR TITLE
[Go] Fix booleans introduction table

### PR DESCRIPTION
**Pull request by angelikatyborska**

### CODE REVIEW

**Review by kotp — APPROVED** [review]

**Review by ErikSchierboom — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Apparently `format.sh` does not use the same prettier version as the workflow 🤔

**Comment by angelikatyborska** [comment]
Oh, so my local prettier version is wrong? I didn't know I had to set the `EXERCISM_PRETTIER_VERSION` env var. That explains why I would constantly change those three files when running `format.sh`. I guess now the PR is not so much about reformatting, but fixing golang's booleans table :)

**Comment by ErikSchierboom** [comment]
Yeah, this is definitely not a great setup to be honest. Sorry about that.

**Pull request merged**
