### PR TITLE
Add missing concepts files

### PR DESCRIPTION
**Pull request by SaschaMann**
This turns half the tests on master green and would allow us to set this check to required so that no new exercises can be added anymore unless they create at least stubs for the concepts files.

It'll save us all dozens of build failure notifications as a nice side effect ;)

### CODE REVIEW

**Review by SleeplessByte — APPROVED** [review]
🤷🏽

**Review by cmcaine — APPROVED** [review]
One day iHID will notice all the warez we're uploading, but probably not today :)

**Review by valentin-p — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
Brilliant @SaschaMann!

**Pull request merged**
