### PR TITLE
[Elixir] Extract Concepts from v2 exercise: robot-simulator

### LINKED ISSUE #299: [Elixir] Extract Concepts from v2 exercise: robot-simulator
Extract the list of concepts required to solve the v2 Elixir exercise: `robot-simulator`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/elixir/exercises/robot-simulator/solutions`). The goal of this task is to help determine the total list of concepts that make up `robot-simulator`.

The list of concepts should be stored in the following document: `languages/elixir/reference/exercise-concepts/robot-simulator.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/elixir/reference/exercise-concepts/robot-simulator.md

### PR DESCRIPTION
**Pull request by filalex77**
Close #299.

---
This change is [Reviewable](https://reviewable.io/reviews/exercism/v3/861)

### CODE REVIEW

**Comment by neenjaw** [comment]
This looks good, are there any of these concepts missing from the elixir language reference?

**Comment by neenjaw** [comment]
I will approve when I get to my laptop, can't approve from my phone.

**Comment by filalex77** [comment]
Thanks, I forgot to cross-reference the CSV with `README.md`. Will do now. Also, I will rename my concepts to existing names (like `pipe-operator` ⇒ `pipelines`).

**Comment by neenjaw** [comment]
I'm not sure we have a csv started yet, if you bootstrap one that would be awesome.

**Comment by filalex77** [comment]
@neenjaw Sorry, mixed it up. Just did a CSV file for Rust :)

By CSV I meant "these concepts". I can do the CSV soon, no problem.

**Comment by neenjaw** [comment]
Heh, ok, LGTM

**Pull request merged**
