### PR TITLE
[C#] First draft of Arrays concept

### PR DESCRIPTION
**Pull request by MarkusReynolds1989**
Initial concept for [Arrays Concept Exercise](https://github.com/exercism/v3/issues/33)

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@MarkusReynolds1989 Could you give some examples of what the input would look like to the various methods? To get a feel for it.

By the way, this type of exploratory PR is very nice. I'm thinking that maybe the GitHub issue itself is where we should be discussing the story/theme and what this would look like. Would you mind posting your thoughts on this exercise in the GH issue?

**Comment by aimorris** [comment]
Hello @MarkusReynolds1989. Are you still actively working on this PR and the issue it addresses? If so, keep up the good work! Otherwise, please advise :)

**Comment by MarkusReynolds1989** [comment]
Hey everyone, I was on a hiatus there with coming back from overseas and this Covid19 stuff for work. Let me go over to the issue page and review everything again, get caught back up, and I'll start working on this again. I'll also jump back on the pattern matching one.

**Comment by ErikSchierboom** [comment]
@MarkusReynolds1989 It would indeed be wise to re-read the issues, as they've changed a bit. There is now also a [JavaScript PR for an arrays exercise](https://github.com/exercism/v3/pull/1033), which we could perhaps use to port from.

I'd like to suggest discussing your plans a bit before starting to work on this again, just to be sure we're on the same page :)

**Comment by ErikSchierboom** [comment]
@MarkusReynolds1989 has indicated he doesn't have time to work on this PR at the moment. Thanks for your hard work!

I'll close this PR in favor of https://github.com/exercism/v3/pull/1257.

**Pull request closed without merging**
