### PR TITLE
[Reference] Adding to general reference

### PR DESCRIPTION
**Pull request by neenjaw**
@ErikSchierboom I'm not sure who to tag this one for reviewers as this is the first new reference I have submitted.

---

This expands upon the UTF7 and UTF8 references

Also adds lazy and eager computation

Also adds actor model

### CODE REVIEW

**Comment by neenjaw** [comment]
Yes, I attributed some of them according to what I saw consistent in some of the other documents. If you have a preferred attribution format I can amend for it.

**Comment by ErikSchierboom** [comment]
@neenjaw Oh, it's just that I don't know if we had decided upon a format :D It's probably correct, but @iHiD will know.

**Comment by iHiD** [comment]
We need to resolve https://github.com/exercism/v3/issues/163

**Comment by neenjaw** [comment]
Sounds good, I'll try keep an eye out for a resolution on that thread.

**Comment by neenjaw** [comment]
@SleeplessByte, @kotp 

Since you two were the other main participants in #163 and @ErikSchierboom is on holidays -- does this match the style we are going for now?

**Comment by kotp** [comment]
> I used zoterobib as @kotp had mentioned in the discussion and the format it spat out matched similarly so I made an assumption.

I usually use "Science of Computer Programming" citation style.

**Comment by kotp** [comment]
```
[1]UTF-16, Wikipedia. (2020). https://en.wikipedia.org/w/index.php?title=UTF-16&oldid=940679308 (accessed March 1, 2020).
```

This would be my preferred (as from the "Science of Computer Programming" citation style, but because the words used make it known, you don't have to assume "published, or accessed" it says so.)  That said, as long as the citation is there, and you can get to the material (not behind a paywall) that information can probably be easily gleaned.

**Comment by neenjaw** [comment]
Ok, i'll edit them to match that in the AM.  Thanks for response! most appreciated.

**Comment by neenjaw** [comment]
updated to 'Science of Computer Programming' style, still good to go?

**Comment by kotp** [comment]
I like it, any objections?

**Pull request merged**
