### PR TITLE
[Julia] Convert existing files to new repository structure

### PR DESCRIPTION
**Pull request by SaschaMann**
@ErikSchierboom could you please take a look if "Convert existing files to new repository structure" is done or if I've missed anything?

### CODE REVIEW

**Comment by SaschaMann** [comment]
Fixed, thanks for the review :)

**Comment by ErikSchierboom** [comment]
It looked like the verify-links action hanged, so I tried to do another rebase.

**Comment by ErikSchierboom** [comment]
@iHiD I can't merge this due to the verify-links action not finishing. Could you take a look if you can merhe?

**Comment by iHiD** [comment]
@ErikSchierboom I added another commit to nudge it.

**Comment by ErikSchierboom** [comment]
Thanks!

**Pull request merged**
