### PR TITLE
Deleting try-rescue-else-after concept

### PR DESCRIPTION
**Pull request by jwarwick**
Will add this info to the `try-rescue` concept in PR #2387.

### CODE REVIEW

**Comment by angelikatyborska** [comment]
Hmm... we designed concept exercises so that `RPNCalculator` (exercises/concept/errors) teaches about `try-rescue` and then `RPNCalculator.Output` (exercises/concept/try-rescue-else-after) teaches about the `else-after` options of try-rescue`. Now that we are switching the concept of v3 to focus on concepts instead of concept exercises, and each concept needs a stand-alone description, I see how it's weird to have both `try-rescue` and `try-rescue-else-after` as separate concepts. But what will we do about those two concept exercises? Is there any way to merge them into one? @neenjaw What do you think about this?

**Comment by neenjaw** [comment]
I would vote  keep them separate for now. They are big exercises if I recall correctly.

**Comment by neenjaw** [comment]
Maybe the concept needs a different name, since they focus on different things. 

 `error-handling` instead of `try-rescue`

That way we don't feel as though we are being repetitive.

**Comment by jwarwick** [comment]
Similar to #2510, I'll leave the current structure as is and we can clean it up after the basic migration.

**Pull request closed without merging**
