### PR TITLE
[Swift] string-components - replace about.md file with concept files

### PR DESCRIPTION
**Pull request by ErikSchierboom**
In [this issue](https://github.com/exercism/v3/issues/2293) we're describing an evolution of the specification of this repo.
    These changes include, amongst others, replacing the contents of the `after.md` document with individual concept documents. There are two documents per concept:

    1. An `about.md` file containing the description of the concept
    1. A `links.json` file containing a set of useful links related to the concept. 

    This looks as follows in the repo:

    ```
    <track>
    ├── concepts
    │   ├── <concept>
    │   │   ├── about.md
    │   │   └── links.json
    │   └── ...
    ```

    This PR applies this change to this exercise by: 
                    
    1. Copying the existing `after.md` file's contents to the `about.md` file of each concept listed in the exercise's `concepts` section in the `config.json` file.
    1. Extract the links from the `after.md` file and put them into the `links.json` file

    Before merging this PR, please check that the contents of the concept documents makes sense.
    This is especially true when the exercise unlocks multiple concepts, as then the concept documents should be updated to only contain the information relevant to that concept.

    Note: to make reviewing easier, the PR has been split into three separate commits. Please squash this PR upon merging.

### CODE REVIEW

**Comment by wneumann** [comment]
This one is going to need a big rewrite. I'll get to it after the easier pickings are done.

**Review by wneumann — APPROVED** [review]
Cleaned up post-reorg. Specific notes are in the commit message.

It should be fine to merge now. There are dead links checks failing, but those don't appear to be in any of the files in this batch.

**Comment by ErikSchierboom** [comment]
There is an invalid link, but that is not caused by this PR. It will be fixed in https://github.com/exercism/v3/pull/2567. Once that is merged, this can be rebased and should be good to go.

**Comment by wneumann** [comment]
Closing. Superseded by https://github.com/exercism/v3/pull/2781.

**Pull request closed without merging**
