### PR TITLE
[Elixir] Graphic Concept Map

### PR DESCRIPTION
**Pull request by neenjaw**
This is a rudimentary start on a concept map for the elixir track.

We have been able to grow a reasonable number of concepts from our exploration of some of the current exercises (#488, #482, #453, #452) resulting in a starting list of concepts (#448, #505).  While the list may be incomplete, in order to accomplish the next task of creating concept implementation guides, we need to begin to place an order to the concepts so that we can design the exercises with a progression in mind.

Quick link to the [graphic concept map in the latest commit](https://raw.githubusercontent.com/exercism/v3/e253e0d1ac825ae4525de140668cd68e17d358da/languages/elixir/reference/concept-map.png)

Please feel free to add/edit to this concept map so that we can move forward together on this.

The PNG is generated from graphviz

---

Known deficits:
- connecting metaprogramming into the pathway

---

Plan for the result of this to be used for #839

### CODE REVIEW

**Comment by neenjaw** [comment]
Given the complexity of this map, probably will need to ordered by hand at some point since there isn't a good way in mermaid to order the subgraphs.

It seems that the variable concept might be the entry point for us.

The go-track is scaffolding out problems so that the student only needs to focus in and complete the concept being taught.

**Comment by devonestes** [comment]
Would graphviz give us a nicer graph if that other thing doesn’t? That’s one piece of software that’s never let me down!

**Comment by neenjaw** [comment]
Ya, I think we will probably need to degree of detail required by graphviz.

I want to be able to draw links from a concept to a subgraph and a subgraph to a concept for better granularity.  I'll work on converting this.

**Comment by neenjaw** [comment]
I think this is nicer now, will have better flexibility for future additions

**Comment by neenjaw** [comment]
Have been watching some of the submissions and i have tried to add some of the concepts I have seen discussed.  There might be a few more.  Anyone have any comments about this progression so far?

**Comment by Cohen-Carlisle** [comment]
I favor going for quality over quantity. If it were up to me, I would cut down the number of concepts to a core set and focus on those. We can always add more concepts later if we think there are core competencies missing. How do others feel about this?

**Comment by neenjaw** [comment]
I think that's fine, and we could always rearrange and/or triage the order of exercises for this purpose.  Where/what would you cut?

**Comment by Cohen-Carlisle** [comment]
I can open a PR against our concepts to segregate core and supplemental concepts.

**Comment by neenjaw** [comment]
That would be great. Then can either revise this graph or triage what to complete first based on that.

**Comment by neenjaw** [comment]
This is diverging farther from our current goal/state, I am going to close this PR to focus more on exercises.

**Pull request closed without merging**
