### PR TITLE
Added description of functional programming

### PR DESCRIPTION
**Pull request by sgedye**

### CODE REVIEW

**Comment by sgedye** [comment]
Thanks :) Yes, it was an amalgamation of what I already knew, with the below resources:

- "Functional Programming": https://en.wikipedia.org/wiki/Functional_programming
- "What is Function Programming | easy way": https://www.youtube.com/watch?v=dAPL7MQGjyM
- "What is Functional Programming": https://www.youtube.com/watch?v=KHojnWHemO0
- "OO vs FP in TypeScript": https://www.youtube.com/watch?v=fsVL_xrYO0w

Do you think it is worth linking them all?

**Comment by neenjaw** [comment]
For sure! 

For referencing we have been using zoterobib.com, a description of the citation style is [>here<](https://github.com/exercism/v3/blob/9c507430f84f8c39b5c2c278324889c44b69fe75/docs/maintainers/faqs.md#should-i-use-citations)

**Comment by neenjaw** [comment]
If you can add those with those references I would happily approve so you can get it merged in!

**Comment by sgedye** [comment]
Thanks for the link, I've added the references :)

**Comment by neenjaw** [comment]
So great! awesome!

**Comment by sgedye** [comment]
Screen Shot 2020-05-19 at 10 30 42 PM

**Comment by neenjaw** [comment]
Sorry, I thought you did with approval, can do!

**Comment by sgedye** [comment]
Great, thanks for all your help neenjaw. This was my first ever PR 😄

**Comment by neenjaw** [comment]
You coulda fooled me, great work!

**Pull request merged**
