### PR TITLE
[CI][Julia] Fix incorrect indentation enforced by prettier

### PR DESCRIPTION
**Pull request by SaschaMann**
#1367 introduced a bug where a CI check enforced incorrect indentation levels for the Julia directory.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@SaschaMann "introduced a bug" I disagree with this statement ;)

By the way, if I read the [documentation](https://prettier.io/docs/en/configuration.html) correctly, you could also add a `.prettierrc` file to the `languages/julia` directory:

> The configuration file will be resolved starting from the location of the file being formatted, and searching up the file tree until a config file is (or isn't) found.

I think I would prefer that. Could you see if that works?

**Comment by SaschaMann** [comment]
> I think I would prefer that.

Same, I didn't know that was an option. I'll try.

**Comment by SaschaMann** [comment]
I don't know if it just overrides options or if it treats it as an entirely new config file, so I copied `semi` and `singleQuote`. Ideally it would just override, imo.

**Pull request merged**
