### PR TITLE
[Elixir] Extract Concepts from v2 exercise: bank-account

### LINKED ISSUE #300: [Elixir] Extract Concepts from v2 exercise: bank-account
Extract the list of concepts required to solve the v2 Elixir exercise: `bank-account`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/elixir/exercises/bank-account/solutions`). The goal of this task is to help determine the total list of concepts that make up `bank-account`.

The list of concepts should be stored in the following document: `languages/elixir/reference/exercise-concepts/bank-account.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/elixir/reference/exercise-concepts/bank-account.md

### PR DESCRIPTION
**Pull request by filalex77**
Close #300.

### CODE REVIEW

**Comment by neenjaw** [comment]
Looks good!

/format

**Comment by filalex77** [comment]
@neenjaw `prettier -c` reports no deviations from the style.

**Comment by neenjaw** [comment]
I think they are working on a third party action runner to make things work on forks, but I'm not sure where it's at.

Thanks for checking the prettier formatting.

**Comment by neenjaw** [comment]
LGTM!

**Pull request merged**
