### PR TITLE
[CoffeeScript] Add @aimorris to contributing maintainers

### PR DESCRIPTION
**Pull request by aimorris**

### CODE REVIEW

**Comment by ferhatelmas** [comment]
@ErikSchierboom I was able to merge for @exercism/coffeescript but was removed a few minutes ago, is it possible to recover? I will also add myself next to @aimorris. It's always more fun to have more people. Thanks!

**Comment by aimorris** [comment]
@ferhatelmas Add yourself to the `config/maintainers.json` in the CoffeeScript repo. You'll automatically get the right perms when I merge it.

**Comment by ErikSchierboom** [comment]
Yes, what @aimorris said!

**Comment by ferhatelmas** [comment]
thanks both, added https://github.com/exercism/coffeescript/pull/113

**Pull request merged**
