### PR TITLE
[Python] Concept References - Update with Code Examples

### PR DESCRIPTION
**Pull request by BethanyG**
Updated `matrix.py` and `markdown.py` to include the text of code examples that are otherwise behind a username on `exercism.io`

### CODE REVIEW

**Comment by BethanyG** [comment]
Apologies for the delay.  Should I have squashed and merged as I updated to avoid the commits from other tracks?  LTM - I am happy to re-do.

**Comment by yawpitch** [comment]
Ye gods ... looks like you synced your fork, then pushed ... I think I'll need to merge in the changes in the master branch into this branch, that "should" clear it up.

**Comment by yawpitch** [comment]
... or not entirely.

I _think_ you need to sync your fork and rebase your 2 most recent commits on top of the current upstream/python-concept-exercises ... but honestly we may be better off just letting me pick out the two files changed and manually pull in the changes.

**Comment by BethanyG** [comment]
Egads.  Let's just close this as a horrid mess we won't speak of again.  The changes were just the code examples, and I can get those to you manually.  Meanwhile, I will send myself back to git school and get my fork  cleaned up so that this doesn't happen again..

**Comment by yawpitch** [comment]
Right ... I can already get the changed files from the PR. I'll grab the changes and push, then we can delete this and never speak of it again.

**Pull request closed without merging**
