### PR TITLE
[C#] consolidate references to arithmetic-overflow and overflow

### PR DESCRIPTION
**Pull request by mikedamay**

### CODE REVIEW

**Comment by mikedamay** [comment]
as per #2298 

As of now _csharp/config.json shows:
- `overflow` concept
- `arithmetic-overflow` concept
- `hyperinflation-hits-hyperia exercise` introduces `overflow` concept (_design.md_ is consistent)
- `instruments-of-texas` exercise introduces `user-defined-exceptions` concept and takes `arithmetic-overflow` as a prerequisite (_design.md_ is consistent)

In addition:
- concept directories exist for both `arithmetic-overflow` (empty) and `overflow` (complete) 

I propose to:
- delete the empty _arithmetic-overflow_ files and directory 
- rename the dependency in _config.json as `overflow`
- delete the `arithmetic-overflow` concept entry from _config.json_.

If on further consideration the team would prefer the concept to be `arithmetic-overflow` then we can do mass rename in a separate PR.

**Comment by mikedamay** [comment]
I have:

I propose to:
- deleted the empty _arithmetic-overflow_ files and directory 
- renamed the dependency in _config.json as `overflow`
- deleted the `arithmetic-overflow` concept entry from _config.json_.

**Review by ErikSchierboom — APPROVED** [review]
LGTM!

**Comment by mikedamay** [comment]
thnx

**Pull request merged**
