### PR TITLE
[Csharp] resolve cyclic dependency with exceptions and overflow

### PR DESCRIPTION
**Pull request by valentin-p**
#2282

removing overflow prerequisite from the exceptions concept exercise, we do not need to know about the overflow in detail to understand try catching exceptions

### CODE REVIEW

**Comment by mikedamay** [comment]
This is a good catch.

I think that if we are removing `overflow` as a prerequisite from `exceptions` then we should avoid having `overflow` in the story/code.

My suggestion would be to substitute `System.Text.Json.JsonException` exceptions as the basis of the story.  Another candidate is `System.InvalidTimeZoneException`.

We want something that is 
- quasi-realsitic
- simple to understand and implment
- avoids using exceptions as part of the workflow which is generally considered bad practice (although I think this principle is a little muddle-headed).

Other suggestions welcome.

**Comment by valentin-p** [comment]
Question: 
Should we merge the arithmetic-overflow (in \languages\languages.json and in config.json "slug": "user-defined-exceptions") and the overflow concept names? If so, which "slug" do we keep ?

Another option would be to keep the current story about a simple calculator and move the checked{} keyword over to the concept exercise overflow/arithmetic-overflow.
Option 1. Change the type to double handle only exceptions: DivideByZeroException and NotFiniteNumberException

Possible exceptions to introduce in a story for concept exercise exceptions: `IndexOutOfRangeException`, `ArgumentOutOfRangeException` ,`ArgumentNullException`,  `FormatException` and `DivideByZeroException`

Need to know exceptions: `Exception`, `InvalidCastException`, `NullReferenceException`, `InvalidOperationException`, `ArgumentException`, `StackOverflowException`

**Comment by ErikSchierboom** [comment]
> My suggestion would be to substitute System.Text.Json.JsonException exceptions as the basis of the story. Another candidate is System.InvalidTimeZoneException.

I'd argue against using ` System.Text.Json.JsonException`, as that would have the students use the `System.Text.Json` code and I'd prefer not to introduce JSON handling in the exercise.

> Another option would be to keep the current story about a simple calculator and move the checked{} keyword over to the concept exercise overflow/arithmetic-overflow.

I'd prefer to keep the existing `overflow` exercise, as I really like that exercise and its focus on just overflows.

> Option: Change the type to double handle only exceptions: DivideByZeroException and NotFiniteNumberException

That could work, although is does start to look quite a bit like the `overflow` exercise then. Maybe we need to re-think the `exceptions` exercise a bit and possibly also the `user-defined-exceptions` exercise.

@mikedamay what are your thoughts on the above?

**Comment by mikedamay** [comment]
> Should we merge the arithmetic-overflow (in \languages\languages.json and in config.json "slug": "user-defined-exceptions") and the overflow concept names? If so, which "slug" do we keep ?

To avoid complicating things I have raised issue #2298 to rename the dependency in _csharp/config.json as `overflow`.  Please add a discussion of which is a better name/slug in that issue - I am easy.

**Comment by mikedamay** [comment]
> Possible exceptions to introduce in a story for concept exercise exceptions: IndexOutOfRangeException, ArgumentOutOfRangeException ,ArgumentNullException, FormatException and DivideByZeroException

I rejected these sorts of exceptions because I have never written code that catches them so they fail the "quasi-realistic" test.  However, it's that sort of thinking that got us into this pickle.

**Comment by mikedamay** [comment]
> hat would have the students use the System.Text.Json code 

Not if we provide all the JSON stuff.  The student would be required to take the parameter passed in from the tests and pass them into our "library" handling any JSON exception.

**Comment by mikedamay** [comment]
We could think about:

- `InvalidOperationException`
- `NotFiniteNumberException` as suggested by @valentin-p .

**Comment by ErikSchierboom** [comment]
Maybe the `InvalidOperationException` could be useful? I've used that quite a bit. We could even use the `NotImplementedException` and come up with a story around working with another department's library that is still being implemented. The story could be to get a progress report or something like that, in which the student checks which features are "complete" (as in: implemented).

**Comment by mikedamay** [comment]
Let's merge this to get rid of the cyclical dependency.  I have raised issue #2314 to change the story in line with @ErikSchierboom 's suggestion above.

**Review by mikedamay — APPROVED** [review]
See comment above re issue #2314

**Comment by ErikSchierboom** [comment]
Thanks @valentin-p!

**Pull request merged**
