### PR TITLE
[C#] Extract concepts from v2 exercise: high-scores (new)

### PR DESCRIPTION
**Pull request by fpetru**
Ref #721 - new PR

### CODE REVIEW

**Comment by fpetru** [comment]
@ErikSchierboom - please review and approve this is a new PR. As soon as this will be approved, I will close the earlier one (#722).

**Comment by ErikSchierboom** [comment]
@fpetru Done!

**Comment by senal** [comment]
@fpetru,
You have done a great job structuring the page.
Should we follow the same structure for other concepts?
Please advise.

**Comment by ErikSchierboom** [comment]
@senal No, we should not. The structure is not really that important to us for the v2 exercises, it is just the Concepts we are interested in.

**Pull request merged**
