### PR TITLE
[Go] Add new Concept Exercise: errors

### LINKED ISSUE #846: [Go] Implement new Concept Exercise: errors
[Use this issue template to describe how to implement a new concept exercises. Please fill in the issue template, and remove any sections wrapped in square brackets (such as this section!).]

This issue describes how to implement the `errors` concept exercise for the Go track.

## Getting started

**Please please please read the docs before starting.** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. So, before diving into the implementation, please read up on the following documents:

- [The features of v3](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md).
- [Rationale for v3](https://github.com/exercism/v3/blob/master/docs/rationale-for-v3.md).
- [What are concept exercise and how they are structured?](https://github.com/exercism/v3/blob/master/docs/features-of-v3.md)

Please also watch the following video:

- [The Anatomy of a Concept Exercise](https://www.youtube.com/watch?v=gkbBqd7hPrA).

## Goal

The goal of this exercise is to teach the student how to work with `errors` in Go.

## Learning objectives

- Create new errors (errors.New)
- create formatted errors (fmt.Errorf)
- correct format of error message (not capitalized, no punctuation at the end)
- wrap error messages manually with colon
- error constants (usually exported so they can be checked against)
- error is always the last return parameter.

## Out of scope

- error handling (checking for errors)
- wrapping/unwrapping
- custom error types

## Concepts

- `errors.basic`

## Prerequisites

- `constants`, `types`

## Resources to refer to

- https://golang.org/pkg/errors/

## Help

If you have any questions while implementing the exercise, please post the questions as comments in this issue.

### PR DESCRIPTION
**Pull request by micuffaro**
Fixes #846

A draft of the errors concept ex.
I've gone with something simple like the answer to life from Hitchhiker's guide to the galaxy. 
The context of the exercise may be changed (suggestions welcome), but I believe it does demonstrate the usage of `error` according to the objectives.

Thoughts?

### CODE REVIEW

**Comment by tehsphinx** [comment]
Note: let's get the example done first. Then we merge and go from there. Better a few steps than a huge PR that takes ages until all is polished to perfection :)

**Comment by micuffaro** [comment]
@tehsphinx , Thank you for the precious feedback! I have taken it on board and updated the sample by adding more functions, which touch on different learning objectives for this concept.

I am still not convinced about the "story" though, referencing a sci-fi book that not everyone has read maybe isn't that relatable. I will try to come up with something.

**Comment by tehsphinx** [comment]
> I am still not convinced about the "story" though, referencing a sci-fi book that not everyone has read maybe isn't that relatable.

I'll let you come up with a new story then as it greatly influences the example...

**Comment by micuffaro** [comment]
Well, I cannot really come up with anything at the moment. Wanna merge it as is for the time being? (assuming it's looking good on your end)

**Pull request merged**
