### PR TITLE
[Java] Extract concepts from v2 exercise: leap

### PR DESCRIPTION
**Pull request by pdmoore**
First pass at this. Appreciate any feedback.

### CODE REVIEW

**Comment by pdmoore** [comment]
> good work @pdmoore , I have only a suggestion: maybe you can add the concept `Argument`.

Thx - Wasn't sure whether I was using the wrong term, a search turned up this
https://www.geeksforgeeks.org/argument-vs-parameter-in-java/

Should we add both concepts `argument` and `parameter` for exercises that are passed values?

**Comment by mirkoperillo** [comment]
@pdmoore I watch the reference exercise again and you have right: `parameter` concept is enough

**Comment by pdmoore** [comment]
> Very extensive, good work.
> 
> I think you can probably be briefer to lower time consumption.

Thanks for the feedback.  I'll try to balance time spent on my side against providing a lot guidance for new developers. Hoping I can reuse many of the general concepts on the next examples,

**Comment by pdmoore** [comment]
Used some minor tweaks to the styling to help get used to the workflow on this project.

Also, need to remember to view the file as html, not text, before I think I'm done!

**Comment by mirkoperillo** [comment]
Hi @pdmoore I think it is time to merge this PR
If you have other modifications, please re-open the issue and create a new PR ref to it.

**Comment by pdmoore** [comment]
@mirkoperillo I don't think I can merge - I don't see the Mrge button, but do see a message "Only those with write access to this repository can merge pull requests". 
There is a "Close and comment" button here but I don't think that does a merge (?).

**Comment by msomji** [comment]
@pdmoore Thats odd, maybe ask @iHiD or @ErikSchierboom to get you access? I'll merge it for you in the mean time

**Comment by iHiD** [comment]
@pdmoore Are you in the maintainers.json file on the Java repo?

**Comment by pdmoore** [comment]
> @pdmoore Are you in the maintainers.json file on the Java repo?

Yes, everything looks correct there

**Comment by pdmoore** [comment]
> @pdmoore Thats odd, maybe ask @iHiD or @ErikSchierboom to get you access? I'll merge it for you in the mean time

Thanks! I'll take a pass at another one, will keep an eye out for what may be the problem

**Comment by iHiD** [comment]
> Yes, everything looks correct there

@pdmoore I don't see you there: https://github.com/exercism/java/blob/master/config/maintainers.json

**Comment by pdmoore** [comment]
@iHiD 
I was looking at the v3 project maintainers, not the live one - should I be added to the one you referenced?
https://github.com/exercism/v3/blob/master/languages/java/maintainers.md

**Comment by iHiD** [comment]
You should be added to the one I mentioned :)

**Pull request merged**
