### PR TITLE
[CI] Match on all JSON files

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by neenjaw** [comment]
I think @SaschaMann stated that in the GH actions DSL, these are equivalent

**Comment by neenjaw** [comment]
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-including-paths

**Comment by SaschaMann** [comment]
The docs say they're equivalent but apparently they're not. Erik also updated the markdown files https://github.com/exercism/v3/pull/1329

**Comment by neenjaw** [comment]
Interesting.

**Comment by ErikSchierboom** [comment]
It looks a bit like a bug. Just to be on the safe side, I'd like to merge this.

**Pull request merged**
