### PR TITLE
[Factor] Initial Factor bootstrap

### PR DESCRIPTION
**Pull request by catb0t**
This is just from copying the csharp directory, there's nothing here brought over from the https://github.com/exercism/factor repository yet, but there will be. 

So far I've Factor-ized stuff outside `exercises/`, just as a skeleton.

### CODE REVIEW

**Comment by iHiD** [comment]
@erikschierboom has a script to give you a clean bootstrapped section without the noise. He'll do that for you when he's next working :)

**Comment by catb0t** [comment]
I saw that ["open an issue here"](https://github.com/exercism/v3/blob/79f47bf8ab41b9913fa63b946898bf05929e29b9/languages/README.md) and then I read [the new v3 track README](https://github.com/exercism/request-new-language-track/blob/master/README.md) which says to open an issue (for myself, the sole maintainer) in [exercism/factor](github.com/exercism/factor), or ask for it to be created as a new track,  but the track is already known to Exercism -- that's why I didn't.

Thanks though, shall I close this and wait for the bootstrapped directory to appear in master?

**Comment by iHiD** [comment]
The test in bold here at the top is what I hoped maintainers would see first: https://github.com/exercism/v3/blob/master/docs/maintainers/README.md

If you could open an issue for it to be bootstrapped then Erik will do it for you. Or you can leave this open to act as that request/reminder :)

**Comment by catb0t** [comment]
Ah, I guess I read that as applying to completely non-pre-existing tracks only.

**Comment by ErikSchierboom** [comment]
I'll close this PR in favor of #192. Thanks for working on Factor @catb0t!

**Pull request closed without merging**
