### PR TITLE
[Julia] Extract concepts from robot-name

### LINKED ISSUE #324: [Julia] Extract Concepts from v2 exercise: robot-name
Extract the list of concepts required to solve the v2 julia exercise: [`robot-name`](https://github.com/exercism/julia/tree/master/exercises/robot-name). For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches ([published community solutions](https://exercism.io/tracks/julia/exercises/robot-name/solutions)). The goal of this task is to help determine the total list of concepts that make up `robot-name`.

The list of concepts should be stored in the following document: `languages/julia/reference/exercise-concepts/robot-name.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/julia/reference/exercise-concepts/robot-name.md

---

**v2 Metadata**

```
core
  → true

difficulty
  → 5

topics
  → randomness
  → strings
  → structs
```

### PR DESCRIPTION
**Pull request by SaschaMann**
Fixes #324

### CODE REVIEW

**Comment by SaschaMann** [comment]
@ErikSchierboom Should these files have solely concepts required to solve the exercise in an idiomatic way or also concepts that can be used to solve it?

**Comment by ErikSchierboom** [comment]
@SaschaMann In principle, I'd go for the concepts required for the idiomatic way. If you feel like including alternative, equally valid approaches, that would be fine too, but the idiomatic approach is by far the most important.

**Comment by SaschaMann** [comment]
thanks for clarifying

**Comment by SaschaMann** [comment]
Sorry for the notifications, I rebased the concept ci branch into this and somehow that triggered the requests

**Pull request closed without merging**
