### PR TITLE
[Docs] remove TODOs from Rust reference

### LINKED ISSUE #1023: [Rust]: remove TODO's from reference documentation
As we get closer to launch we'll want to itemize work in GitHub issues for visibility.
So let's remove the TODO section in the reference readme:
https://github.com/exercism/v3/blob/f3bb9cd2a8603ae6c26f93d1b6b4e81db749b98c/languages/rust/reference/README.md#todo

It seems many of the tasks there are part of the `.docs` requirements while implementing a concept exercise. Where that is not the case, we can add guidelines to the concept exercise implementation guide: https://github.com/exercism/v3/blob/f3bb9cd2a8603ae6c26f93d1b6b4e81db749b98c/languages/rust/reference/implementing-a-concept-exercise.md

### PR DESCRIPTION
**Pull request by efx**
Any work should be itemized as GitHub issue so we can delegate
appropriately and have an idea of what is left. Given our need to
complete more concept exercises I have removed this list. The general
tasks can be included as part of our contribution guide or itemized as
other issues.
Closes #1023.

### CODE REVIEW

**Comment by coriolinus** [comment]
Agree in principle. Will approve once those issues are created.

**Comment by efx** [comment]
> - Finish specifying concept exercises with specific dependencies and topics

I think of this as a meta issue. The collection of concept exercise issues represents progress to that end: https://github.com/exercism/v3/issues/1971

I created https://github.com/exercism/v3/issues/1972 and asked @iHiD and @ErikSchierboom about whether we should do those things.

**Comment by efx** [comment]
@coriolinus any objections to merging this? #1972 captures the needed work.

**Review by coriolinus — APPROVED** [review]
No objections. Sorry for such a long delay; this PR just kind of fell off my radar.

**Comment by efx** [comment]
@coriolinus thank you! It did for me as well. No problem at all.

**Pull request merged**
