### PR TITLE
[Go] add links to existing exercises/documentation: 837

### PR DESCRIPTION
**Pull request by oanaOM**
part of #837 
I've added links for the following exercises:
numbers
basic-strings
+
extra links to general OOP concepts

### CODE REVIEW

**Comment by tehsphinx** [comment]
@oanaOM: Depending on whether you still want to add the slices document to this PR or not, you can merge this.

**Comment by oanaOM** [comment]
Thanks @tehsphinx!  I have added the slice type under reference/types.

**Comment by ErikSchierboom** [comment]
@oanaOM Feel free to merge!

**Comment by oanaOM** [comment]
@ErikSchierboom I would gladly merge it but I don't think I have the rights to do it.
It says "Only those with write access to this repository can merge pull requests."

**Comment by ErikSchierboom** [comment]
@oanaOM Ah okay, I've merged!

**Comment by tehsphinx** [comment]
@oanaOM Thanks! 😊

**Comment by iHiD** [comment]
@oanaOM Would you like to help as a contributing maintainer? If so, @ErikSchierboom can help get you set up :)

**Comment by oanaOM** [comment]
@iHiD I just saw your comment, sorry for the delay reply :(. 
Yes, I would be very happy to help out!

**Pull request merged**
