### PR TITLE
[CoffeeScript] Bootstrap CoffeeScript

### PR DESCRIPTION
**Pull request by iHiD**
If anyone wants to become a CoffeeScript maintainer and pick this up, please add a comment.

### CODE REVIEW

**Comment by SleeplessByte** [comment]
(It's my content, but I don't want to be a CoffeeScript maintainer)

**Comment by Calamari** [comment]
Who is using CoffeeScript anyways :D

**Comment by iHiD** [comment]
Jokes aside, there's going to be a looooot of money to be made by people who are converting CoffeeScript into modern JS in high-usage apps in a few years from now. There's been a lot written in the last few years :)

**Comment by aimorris** [comment]
I'd be happy to take up the role as the CoffeeScript maintainer. I've created a pull request to give myself the correct permissions. https://github.com/exercism/coffeescript/pull/111

**Comment by iHiD** [comment]
@aimorris While I'm super grateful for your enthusiasm, are you not going to get spread pretty thin...? You seem to be everywhere atm! :) Might it be better to focus on a few of the tracks where we need you the most?

**Comment by aimorris** [comment]
I'm currently maintaining PureScript, JavaScript (somewhat), Haskell (rarely), and hopefully CoffeeScript. So I'd have 3 tracks that I'll mainly contribute to, and then Haskell if I have nothing to do.

**Comment by ErikSchierboom** [comment]
@aimorris Great! Just keep an eye on yourself not to overload.

**Comment by iHiD** [comment]
@ErikSchierboom Want to add a commit with some boostrapping to this then?

**Comment by ErikSchierboom** [comment]
@iHiD Done

**Pull request merged**
