### PR TITLE
[C#] Basics concept. detailing variable names

### LINKED ISSUE #1979: [C#] basics add description of @ prefix
Extend the discussion of identifiers in _after.md_ with a brief description of and reference to the @ prefix.  This is a good reference:https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/identifier-names.

### PR DESCRIPTION
**Pull request by valentin-p**
- Add some details to the about file.
- Add the link to the identifier rules.

Edit:
- Mentioning the @ escape character

Close #1979

### CODE REVIEW

**Review by mikedamay — COMMENTED** [review]
I think the new text is definitely an improvement.

The intention with #1979 was to say something about using '@' to allow reserved words such as `@this` or `@var` to be used as identifiers.  I think we need to mention it somewhere in the track and this concept seemed like a good place.

**Comment by valentin-p** [comment]
Mentioning the @ escape character

**Review by mikedamay — APPROVED** [review]
Excellent

**Review by ErikSchierboom — APPROVED** [review]
Great!

**Pull request merged**
