### PR TITLE
[Java] add sshine, mirko, pdmoore and msomji as contributing maintainers

### PR DESCRIPTION
**Pull request by msomji**
@sshine @pdmoore, @mirkoperillo Please double check I got your info correct 😄

### CODE REVIEW

**Comment by sshine** [comment]
@ErikSchierboom: Who's the GitHub Actions wiz around here?

I re-ran the Pull Request Labeler because it failed initially, but it [still fails](https://github.com/exercism/v3/pull/184/checks?check_run_id=397128395):

```
Run actions/labeler@04aa5dbc72538e0b9194c658a9ad6026b865d039
  with:
    repo-token: ***
    configuration-path: .github/labeler.yml
##[error]HttpError: Resource not accessible by integration
##[error]Resource not accessible by integration
##[error]Node run failed with exit code 1
```

I even tried to squash the commits and force push so that there was no intermediate commits with what it could possibly treat as broken links.

**Comment by sshine** [comment]
Removing the `track/java` label that was manually added and re-running the Pull Request Labeler doesn't work either.

**Comment by sshine** [comment]
I tried to resubmit this with the commit/PR title and branch name in order from the start in #185, and this also failed. I checked that the four hyperlinks to GitHub profiles mentioned here do work. So I am finally out of ideas as to why this fails.

I'm hoping someone with better knowledge of GitHub Actions will chime in.

@ErikSchierboom / @SaschaMann?

**Comment by sshine** [comment]
It seems that in spite of Pull Request Labeler failing, I could still merge this.

I'm sorry for the noise created by debugging this when I could just have ignored it.

**Comment by NobbZ** [comment]
Labeler only works for PRs made from within the repo, not for forks, please see actions/labeler#12 for further details.

**Comment by sshine** [comment]
OK, thanks for clarifying, @NobbZ.

That means a contributor will have to decide between pushing their feature branches directly upstream for their pull requests, in which case the labeler will work, or push to their own fork, accept a cryptic error message and label the pull request themselves. I'll probably stick to the latter, but I can understand why people might prefer the former.

**Pull request merged**
