### PR TITLE
[Rust] add concept exercises to our config.json

### PR DESCRIPTION
**Pull request by efx**
Showing off @seanchen1991 's recent work :tada: 
It will up our count in the maintenance [dashboard](https://v3.exercism.io/rust/maintaining/launch) too!

### CODE REVIEW

**Comment by iHiD** [comment]
@coriolinus Yeah - good point. There will do. But atm it would mean people couldn't use the exercise builder (without further modification) on v3.exercism.io as that doesn't yet update the config.json. Once that's been fixed, we'll add an enforcing GH Action.

@ErikSchierboom Maybe you could create an issue with any tracks that have exercises not currently in the config.json, and tag the relevant teams in it pls?

**Comment by ErikSchierboom** [comment]
@iHiD Will do that!

**Comment by ErikSchierboom** [comment]
@iHiD Done: https://github.com/exercism/v3/issues

**Comment by iHiD** [comment]
Thanks :)

**Pull request merged**
