### PR TITLE
[Clojure] Init New Concept Exercise for `List`

### PR DESCRIPTION
**Pull request by bemself**
Initing new concept "List", welcome any comments and suggestions if you have time to give a look at, though it's still in progress, in case i'm going the wrong way, thanks!

### CODE REVIEW

**Comment by porkostomus** [comment]
`clj-kondo` (my linter) is telling me that `remove` and `count` already refer to core functions. This is fine, actually it's done in one of the core exercises (also the `count` fn), but it's not really the best practice and forces them to explicitly call `clojure.core/count` if needed. Might consider more specific names like `remove-item` / `count-list`?

**Comment by bemself** [comment]
@porkostomus yes you are quite right, thanks for it! I've renamed the func names and committed~

**Comment by bemself** [comment]
@porkostomus sorry for the delay of quite some days, finally got time to finish the draft, could you find time to give it a review? thanks~

**Comment by porkostomus** [comment]
Looks great!! It was suggested that we include a `[design.md](https://github.com/exercism/v3/blob/master/languages/csharp/exercises/concept/numbers-floating-point/.meta/design.md)` for exercises that don't have abn accompanying issue, to serve as a record of its structure.

**Pull request merged**
