### PR TITLE
[CI] Filter link checker output

### PR DESCRIPTION
**Pull request by aimorris**
Filters the link checker output to only include lines that are errors.

### CODE REVIEW

**Comment by aimorris** [comment]
#214

**Comment by aimorris** [comment]
Okay I'm not sure why it's failing to run?

**Comment by NobbZ** [comment]
`grep` has a non-zero exit code when no lines match.

`grep`ing this way will only show us the failing link, not the file where it lives.

I'm not sure if that is much better than what we have currently.

**Comment by aimorris** [comment]
Oh yes true. I'll close this PR, it isn't useful.

**Pull request closed without merging**
