### PR TITLE
[C#] Use consistent concept names

### PR DESCRIPTION
**Pull request by ErikSchierboom**

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@SleeplessByte Done. Could you rebase and merge? I've kept the commits per language.

**Comment by SleeplessByte** [comment]
@ErikSchierboom do you know why the link checker is failing?

**Comment by ErikSchierboom** [comment]
@SleeplessByte I have an idea, and the fix is in https://github.com/exercism/v3/pull/251/files (it is about a missing rebase I think, and so improved error handling). But I can't merge that PR yet, as it has not yet been approved :(

**Comment by ErikSchierboom** [comment]
@iHiD It says: "Expected — Waiting for status to be reported" for the action. I think you solved that in another PR this week. How did you do that?

**Comment by iHiD** [comment]
Some times it just hangs. I don't know how to restart GHA actions though, so I just type `/rebase` and hope :)

**Comment by ErikSchierboom** [comment]
So I have no idea how to fix the hanging status. I'm gonna do the prototypical IT solution: delete and retry.

**Comment by iHiD** [comment]
lolz

**Comment by ErikSchierboom** [comment]
And it worked!

**Pull request closed without merging**
