### PR TITLE
[Python] [Draft] Concept Exercise for String-Formatting

### PR DESCRIPTION
**Pull request by J08K**
Just the draft for now :))

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
@J08K Is there anything I can do to help with this PR?

**Comment by J08K** [comment]
> @J08K Is there anything I can do to help with this PR?

I have been quite busy with school (have to make the school's newspaper website and other stuff😅). I will try and get some work on this PR done as soon as possible, but for now I'm alright, thanks!

**Comment by ErikSchierboom** [comment]
Great! Thanks for the reply. Good luck with school!

**Comment by BethanyG** [comment]
Hi @J08K -  @valentin-p has expressed interest in taking this over and re-working it (and our existing `string` and `string-methods` exercises) into a series that uses the same story.  Would that be OK with you?   Please let me know.  Thanks! 🌟

**Comment by BethanyG** [comment]
@valentin-p  - assigning this to you as part of your `str` related editing/rewrite.  LMK if you have questions or issues.  Thanks!  @J08K --  **Thank you so much** for getting this moving and for all your hard work on it!  🎉

**Comment by ErikSchierboom** [comment]
This Friday (Jan 29th 2021), we're going to explode this repo back into the individual track repositories and archive this repo.

As such, this PR needs to be merged by Friday 9am UTC, or it will need to be manually reopened against the track repo.

**Pull request closed without merging**
