### PR TITLE
test uuid = null on tree

### PR DESCRIPTION
**Pull request by tehsphinx**
Shall we quickly test your theory, @TheLostLambda?

### CODE REVIEW

**Comment by iHiD** [comment]
(cc @neenjaw - I believe a lot of this is your magic?)

**Comment by tehsphinx** [comment]
We will see... 😄

**Comment by neenjaw** [comment]
What theory?

**Comment by tehsphinx** [comment]
@neenjaw: We are trying to have a node not show as "implemented" but still be able to have it in the tree already (to discuss the future tree)

**Comment by tehsphinx** [comment]
See #2031

**Comment by tehsphinx** [comment]
Note: setting the uuid to "null" does not seem to work: https://v3.exercism.io/go/maintaining/tree (see mutex node which was changed in this merge request)

**Comment by neenjaw** [comment]
As is, it _should_ show, but I don't think it will appear different from any other exercise

**Comment by neenjaw** [comment]
Mostly because I haven't written that code yet: https://github.com/exercism/v3-dashboard/issues/88

**Comment by tehsphinx** [comment]
Ok... then we'll wait for your improvements!

**Comment by neenjaw** [comment]
If there is a certain _way_ you would like it to be graphically displayed, comment there, I am looking for creative ideas / input.  I am not an experienced UI/UX designer. :hugs:

**Comment by iHiD** [comment]
(A different colour probably suffices absolutely fine for now!)

**Comment by ynfle** [comment]
Adjusting the opacity can also work

**Comment by SleeplessByte** [comment]
Adjusting the opacity isn't as accessible as using a different colour/shape.

**Comment by neenjaw** [comment]
I'm leaning towards a yellow diamond (re-color, rotate of the square).  Probably don't have time to work on this in the next couple of days.

**Pull request merged**
