### PR TITLE
[Elixir] New Concept Exercise: tuples

### PR DESCRIPTION
**Pull request by neenjaw**
This is **draft** PR for a new concept exercise for the elixir track for v3.

I have specifically left it unfinished so that someone new can use it as a scaffold to complete to get experience in the repo.  You may also use it as a scaffold for rolling out your own original exercise.

>@neenjaw

---

# ToDo

- `./lib/`
  - [ ] complete `kitchen_calculator.ex` with stubs for exercise
- `./test/`
  - [ ] write test cases for `kitchen_calculator_test.exs`
  - [ ] add trace and pending tags to `test_helper.exs`
- `./.meta/`
  - [ ] add authors to `config.json`
  - [ ] add example solution to folder named `example.ex`
- `./.docs/`
  - [ ] `introduction.md`
  - [ ] `instructions.md`
  - [ ] `hints.md`
  - [ ] `after.md`
- [ ] update `config.json` with exercise details
- [ ] update `../README.md` with concept details
- [ ] update `/references/...` with concept/implementation details for global reference

# Design

## Goal

The goal of this exercise is to teach the student the basics of tuples and common conventions in elixir to return multiple values.

This is done through implmentation of a kitchen calculator.

## Learning objectives

- Know what a tuple is
- Know how to write a tuple literal
- Know how to return a tuple from a function
- Know how to extract an element from a tuple using `elem/2`
- Know how to write a floating point literal
- Know how to round a floating point number to decimal place or integer

## Out of scope

- pattern matching
  - including parameter deconstruction techniques

## Prerequisites

The exercise's prerequisites are:

- `basics`: needs to be able to define named functions, define and return integers, return values from functions
- `atoms`: needs to be able to define and use atoms for return values

## Concepts this unlocks are:

- `tuples` know of the existence of the `tuple` data type, how to define tuple literals, extract values from a tuple using `elem/2`
- `floating-point-numbers` know of the existence of the floating point number type, know that it is double precision float encoding, how to convert it to an integer type

## Representer

This exercise does not require any specific representation logic to be added to the [representer][representer].

## Analyzer

This exercise could benefit from the following rules added to the the [analyzer][analyzer]:

- Verify common conversion functions aren't used from the standard library if they exist.

[analyzer]: https://github.com/exercism/elixir-analyzer
[representer]: https://github.com/exercism/elixir-representer

### CODE REVIEW

**Comment by neenjaw** [comment]
@ErikSchierboom No need to do a full review at this time if you need to triage your time, have you tagged just so that it isn't missed when it's marked ready for review.

**Comment by ErikSchierboom** [comment]
@neenjaw Ping me when you want a review! Great to work on this.

**Comment by neenjaw** [comment]
@aimorris why remove the `good first issue` and `help-wanted` labels?

**Comment by aimorris** [comment]
> @aimorris why remove the `good first issue` and `help-wanted` labels?

This is a pull request.

**Comment by neenjaw** [comment]
In the header of the pull requests tab github mentions the `good first issue` label for issues and pull requests as a marker for new people to contribute.  It is also a reasonably well recognised as a label across FOSS as an accepted label that people know to search for.  

But even if we were concerned about the potential confusion using the word `issue` on a label for a PR, why then also remove the `help-wanted` label?  Neither are specifically referenced in the repository structure document not to use those labels for this purpose. 

Secondly, I posted this draft PR specifically to provide a scaffold for someone new to contribute to v3 if they felt that the concept exercise structure was overwhelming -- which I can't do in an issue.

Any suggestions for how to direct them to this PR if someone new is looking to contribute?

**Comment by neenjaw** [comment]
I'm closing this to re-open a new draft one based on the the new path to have an initial high-level discussion about the concept exercise.

**Pull request closed without merging**
