### PR TITLE
[Go] zero-value - replace about.md file with concept files

### PR DESCRIPTION
**Pull request by ErikSchierboom**
In [this issue](https://github.com/exercism/v3/issues/2293) we're describing an evolution of the specification of this repo.
These changes include, amongst others, replacing the contents of the `after.md` document with individual concept documents. There are two documents per concept:

1. An `about.md` file containing the description of the concept
1. A `links.json` file containing a set of useful links related to the concept. 

This looks as follows in the repo:

```
<track>
├── concepts
│   ├── <concept>
│   │   ├── about.md
│   │   └── links.json
│   └── ...
```

This PR applies this change to this exercise by: 
                    
1. Copying the existing `after.md` file's contents to the `about.md` file of each concept listed in the exercise's `concepts` section in the `config.json` file.
1. Extract the links from the `after.md` file and put them into the `links.json` file

Before merging this PR, please check that the contents of the concept documents makes sense.
This is especially true when the exercise unlocks multiple concepts, as then the concept documents should be updated to only contain the information relevant to that concept.

Note: to make reviewing easier, the PR has been split into three separate commits. Please squash this PR upon merging.

### CODE REVIEW

**Comment by bitfield** [comment]
I think this needs a little chewing over:

> Unlike some other languages, Go has no empty/null/undefined state for uninitialized variables

The spec is quite clear that `nil` does, indeed, indicate that a variable has not been initialized. Yes, technically speaking it is the "zero value" for pointers, maps, and so on, but I think this is likely to cause some confusion. Consider the difference between a nil map and an empty map, for example.

**Comment by tehsphinx** [comment]
@bitfield: I know what you mean. On the other hand you can't set variables to `nil` that are not a pointers or pointer based. Which you can in those "other" languages.

How'd you express it?

**Comment by ErikSchierboom** [comment]
As we move forward towards v3 launch, this PR now need merging as this PR makes your track adhere to the latest specification. Could you please check whether they’re ok and merge them? If you don’t have time, I’ll merge them mid-next week and we can tidy things up later.

**Review by tehsphinx — APPROVED** [review]
LGTM

**Pull request merged**
