### PR TITLE
Add Elm concept exercises / dependency diagram

### PR DESCRIPTION
**Pull request by ceddlyburge**

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Very cool @ceddlyburge ! @neenjaw you might want to look at this logic too

**Comment by neenjaw** [comment]
:+1::+1::+1::+1: This is very nice, I really like how you've been able to simplify the dependency chain.

**Comment by ceddlyburge** [comment]
Hi @mpizenberg , I've added 'Basics' to the concepts / flow chart, and added a link to the mermaid online editor. Its a faff keeping the base64 encoded text and the normal text up to date (so would probably get out of date over time), so I haven't done this.

I haven't changed the example first / theory first bit, but I have no strong opinion on it so am happy to if you want. Or we can just wait for feedback.

**Comment by mpizenberg** [comment]
All good to me @ceddlyburge ! we should go ahead with that plan for now. It's always possible to revise later. Having this in the readme is a good starting point to get help for concept exercises.

**Pull request merged**
