### PR TITLE
[CI] [Julia] Remove Julia from concept CI

### PR DESCRIPTION
**Pull request by SaschaMann**
It ended up not being as useful as I expected while also being quite fragile. I'd remove it altogether but common-lisp uses parts of it.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
> I'd remove it altogether but common-lisp uses parts of it.

I'd also like to remove this, as it has been a cause of some issues in PR's for other tracks. I'll ask the Common Lisp track how much they are using this.

**Comment by SaschaMann** [comment]
That's for compiling a sysimage and should work regardless because concepts.csv still exists.

**Comment by ErikSchierboom** [comment]
Okay cool.

**Comment by ErikSchierboom** [comment]
@SaschaMann I've had confirmation from the Common Lisp team that it can be removed for them too. So feel free to get rid of this!

**Comment by SaschaMann** [comment]
I hope I didn't miss anything :D

**Comment by ErikSchierboom** [comment]
We'll find out soon enough :)

**Pull request merged**
