### PR TITLE
[Elixir] Concept blurbs and about.md's reviews

### PR DESCRIPTION
**Pull request by angelikatyborska**
WIP

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
This Friday (Jan 29th 2021), we're going to explode this repo back into the individual track repositories and archive this repo.

As such, this PR needs to be merged by Friday 9am UTC, or it will need to be manually reopened against the track repo.

**Comment by angelikatyborska** [comment]
I am 100% ready to redo the PR on my own, manually, against the track repo 👍

**Review by neenjaw — APPROVED** [review]
I'm not sure if this will work since it is draft, but if you want to merge then just improve on it when exploded that is cool too.

**Comment by angelikatyborska** [comment]
@neenjaw Ok, I'll do that!

**Pull request merged**
