### PR TITLE
[C] Extract concepts of v2 resistor-color exercise

### LINKED ISSUE #915: [C] Extract Concepts from v2 exercise: resistor-color
Extract the list of concepts required to solve the v2 C exercise: [`resistor-color`](https://github.com/exercism/c/tree/master/exercises/resistor-color). For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches ([published community solutions](https://exercism.io/tracks/c/exercises/resistor-color/solutions)). The goal of this task is to help determine the total list of concepts that make up `resistor-color`.

The list of concepts should be stored in the following document: `languages/c/reference/exercise-concepts/resistor-color.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/c/reference/exercise-concepts/resistor-color.md

---

**v2 Metadata**

```
core
  → true

difficulty
  → 1

topics
  → enums
  → arrays
  → pointers
```

### PR DESCRIPTION
**Pull request by wolf99**
Closes #915

### CODE REVIEW

**Comment by wolf99** [comment]
@ErikSchierboom I think we saw this problem previously, the concept-test CI check is looking for `concept.csv` which C doesn't have yet. Is there something I can do to fix this?

**Comment by ErikSchierboom** [comment]
@wolf99 That CI script was made by @SaschaMann. @SaschaMann do you have anything planned to fix this issue, or is there something the C track can do to fix it?

More practically, if the only CI check that fails is the Concept CI, feel free to just merge.

**Comment by SaschaMann** [comment]
@ErikSchierboom It's caused by rebasing when recent changes on master are match its triggers. I don't know an immediate fix but I'll look into it when I find time. As long as it only happens occasionally, I think it's best to ignore the check and merge anyway, but feel free to temporarily disable it if it causes too much noise.

**Comment by ErikSchierboom** [comment]
@SaschaMann Thanks for explaining. @wolf99 feel free to merge despite the Concept CI check

**Pull request merged**
