### PR TITLE
fixing typos and Prerequisites

### PR DESCRIPTION
**Pull request by valentin-p**
- Fixing the title Prerequisites with a replace all
- Fixing typos in the csharp track 
- Using behavior instead of behaviour for consistency across the csharp track

@iHiD @ErikSchierboom

### CODE REVIEW

**Review by SaschaMann — APPROVED** [review]
The Julia parts of the PR look good to me

Thanks for fixing these! :)

**Review by coriolinus — APPROVED** [review]
Rust change seems fine. Looks like the majority of changes are the same "Prequisites" -> "Prerequisites" typo fix, so I'll approve on behalf of those.

I'm curious about the submodule addition here, though. Was the addition of `development-environment` intentional?

**Review by ErikSchierboom — APPROVED** [review]
Thanks a lot!

**Comment by iHiD** [comment]
Thank you!

**Pull request merged**
