### PR TITLE
[PureScript] cross off have a kick off discussion in readme

### PR DESCRIPTION
**Pull request by aimorris**
I am the only PureScript maintainer. So I've crossed it off in the readme. We can have the discussion once more maintainers appear.

EDIT: Just found out @spicydonuts is also still actively maintaining PureScript. Still not sure if the discussion should take place or not, though.

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
> EDIT: Just found out @spicydonuts is also still actively maintaining PureScript. Still not sure if the discussion should take place or not, though.

I think it would make sense to do so! You can also invite me to the meeting too.

**Comment by iHiD** [comment]
Yeah. Every track should have a meeting at least with the single maintainer and Erik. If tracks don't have multiple maintainers, then we'll focus on getting some more maintainers in. I think it's going to be very challenging for a track to get to v3 with only one maintainer, so we should focus on the getting maintainers then having the kickoff meeting when that's done.

So I suggest closing this PR for now.

**Comment by sshine** [comment]
> I suggest closing this PR for now

Yes, it may seem unsatisfying to be unable to cross it off, but I think it's probably better to indicate that a conversation has not been had. This leaves the door open for future contributors. A late conversation is better than no conversation at all. Not having an early conversation is unfortunate, but no amount of checking off boxes will give us that. :smile:

**Comment by spicydonuts** [comment]
Makes sense, and please invite me if you have this meeting

**Pull request closed without merging**
