### PR TITLE
[JavaScript] Adding some concepts we need

### PR DESCRIPTION
**Pull request by Calamari**
I just added some concepts that I think are missing in the list. It is still not complete, but it has more now. :)

### CODE REVIEW

**Comment by aimorris** [comment]
Please resolve conflicts.

**Comment by aimorris** [comment]
Any reason why the concept check is failing?

**Comment by SleeplessByte** [comment]
Yes. The `concepts.csv` file is missing!

> ERROR: LoadError: ArgumentError: "./languages/javascript/reference/concepts.csv" is not a valid file

**Comment by aimorris** [comment]
@SleeplessByte Is that something specific to this PR or the Javascript track in general? Can this PR be merged?

**Comment by SleeplessByte** [comment]
It's with the track in general.

**Review by SleeplessByte — CHANGES_REQUESTED** [review]
We've dropped the `-basics` suffix.

**Comment by ErikSchierboom** [comment]
@Calamari Is there anything I can do to help with this PR?

**Comment by ErikSchierboom** [comment]
This Friday (Jan 29th 2021), we're going to explode this repo back into the individual track repositories and archive this repo.

As such, this PR needs to be merged by Friday 9am UTC, or it will need to be manually reopened against the track repo.

**Pull request closed without merging**
