### PR TITLE
[All] Add stubs for concept documents

### PR DESCRIPTION
**Pull request by ErikSchierboom**
As per the [updated specification](https://github.com/exercism/v3/issues/2293), this PR adds a "concepts" directory to each track. Each concept used in a track (see https://github.com/exercism/v3/pull/2320) has its own directory with two files:

1. `about.md`
1. `links.json`

The files currently both have placeholder contents. Their contents will have to be updated later. We'll submit a PR to prepopulate the `about.md` files with the current contents of the `after.md` document (which it will replace). We'll also attempt to do something for the `links.json` file, but we have to firm up the specification for the `links.json` file first.

I'll update the documentation in a separate PR.

### CODE REVIEW

**Review by iHiD — APPROVED** [review]
Sweet. Thanks @ErikSchierboom 🙂

**Review by devkabiir — APPROVED** [review]

**Review by coriolinus — APPROVED** [review]
Seems fine for rust as a start. How were the lists of concepts generated?

**Comment by iHiD** [comment]
>  How were the lists of concepts generated?

They're the concepts in your `config.json`

**Review by neenjaw — APPROVED** [review]

**Review by Prounckk — APPROVED** [review]
LGTM

**Pull request merged**
