### PR TITLE
[Nim] add concept reference documents

### PR DESCRIPTION
**Pull request by ynfle**
@ErikSchierboom @ee7 @anyoneelsethatwants this is my draft for the concepts document. Your thoughts are appreciated

In many places, it is overly detailed. I plan to use this instead of concept issues.

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]
This is a good starting point! Not everything that's listed is actually a concept though, as some things are more like notes about a concept, right?

**Comment by ynfle** [comment]
> Not everything that's listed is actually a concept though, as some things are more like notes about a concept, right?

Yes. Because I plan to use this document as a reference when creating exercises instead of issues, I listed many details here also

**Comment by ee7** [comment]
Fixed some typos.

I agree that the Nim manual (maybe tutorial 1) are probably the most useful reference documents for us.

**Comment by ynfle** [comment]
> I agree that the Nim manual (and maybe tutorial 1) are probably the most useful reference documents for us

Were those comments on my list, general comments or something else?

**Comment by ee7** [comment]
> > I agree that the Nim manual (and maybe tutorial 1) are probably the most useful reference documents for us
> 
> Were those comments on my list, general comments or something else?

Just a comment on:

https://github.com/exercism/v3/blob/c3219ab3a189843127ae384f5d4f4508799fea53/languages/nim/reference/README.md#L5

I think one can definitely create concept exercises using this kind of document as a reference.

**Comment by ErikSchierboom** [comment]
Bump. Just checking what the status is of this PR :0

**Comment by ErikSchierboom** [comment]
This Friday (Jan 29th 2021), we're going to explode this repo back into the individual track repositories and archive this repo.

As such, this PR needs to be merged by Friday 9am UTC, or it will need to be manually reopened against the track repo.

**Pull request closed without merging**
