### PR TITLE
[C#] remove local files committed in error

### PR DESCRIPTION
**Pull request by mikedamay**
remove local files pushed in error.

### CODE REVIEW

**Comment by mikedamay** [comment]
not sure if this is right - I will try a different branch.

**Comment by ErikSchierboom** [comment]
@mikedamay Is there anything I can do to help?

**Comment by mikedamay** [comment]
Thanks, I have raised another PR,  #1763.  It still lists lots of commits that are not relevant.  There are no files involved apart  from the ones I am deleting so I suppose it's OK.  I assume the commits will get squashed.

**Comment by ErikSchierboom** [comment]
> Thanks, I have raised another PR, #1763. It still lists lots of commits that are not relevant. There are no files involved apart from the ones I am deleting so I suppose it's OK. I assume the commits will get squashed.

As there are no changed files, that PR actually doesn't really do anything :)

**Comment by mikedamay** [comment]
Won't it delete the deleted ones - csharp/aa-template?

**Comment by ErikSchierboom** [comment]
Nope. I've create a PR to do that: https://github.com/exercism/v3/pull/1764

**Pull request closed without merging**
