### PR TITLE
[CI] Add check that files in .meta/config.json editor settings exist

### PR DESCRIPTION
**Pull request by SaschaMann**
Note that this is expected to fail until all tracks have added those and it's okay to merge regardless of the fail

### CODE REVIEW

**Comment by SaschaMann** [comment]
(should be rebase-merged)

**Comment by ErikSchierboom** [comment]
> Note that this is expected to fail until all tracks have added those and it's okay to merge regardless of the fail

If we merge this, would all PR's then fail for those tracks?

**Comment by SaschaMann** [comment]
> If we merge this, would all PR's then fail for those tracks?

No the PR will work just fine, it will just show a red X that can be ignored in all PRs until all tracks have fixed it.

**Comment by cmccandless** [comment]
Looks like your branch contains changes that may not be required for this PR. Was that intentional?

**Comment by SaschaMann** [comment]
> Looks like your branch contains changes that may not be required for this PR. Was that intentional?

Which?

It's meant to add the check and then fix it for Julia.

**Comment by ErikSchierboom** [comment]
> No the PR will work just fine, it will just show a red X that can be ignored in all PRs until all tracks have fixed it.

👍

**Review by ErikSchierboom — APPROVED** [review]

**Pull request merged**
