### PR TITLE
[Go] change output formatting in examples comments #2010

### PR DESCRIPTION
**Pull request by oanaOM**
I chose to use `Output:` as formatting. Please let me know if this is alright.

### CODE REVIEW

**Comment by tehsphinx** [comment]
@ErikSchierboom: I just checked, and we have both notations in the Go exercises. Some use `Output:` some use `=>`. Is there an agreement on what to use?

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom: I just checked, and we have both notations in the Go exercises. Some use Output: some use =>. Is there an agreement on what to use?

There is no default across tracks, as we recommend each track to use the format that makes most sense for their track. In some tracks they have a REPL that is used often, so in that case the output format of the REPL is used. As long as it is clear to the student that it is not some function call but actual output and it is consistent across exercises, you can use what you want.

**Comment by ErikSchierboom** [comment]
So the Go maintainers themselves can decide amongst themselves which format to use.

**Comment by tehsphinx** [comment]
@oanaOM: Ok then we go with your choice: `Output:`

**Comment by oanaOM** [comment]
Great! Thanks @tehsphinx for merging this.

**Pull request merged**
