### PR TITLE
[Docs] add badge

### PR DESCRIPTION
**Pull request by ynfle**

### CODE REVIEW

**Comment by kotp** [comment]
I may have merged this prematurely, as it probably initially belonged in "Unsorted Ideas".

**Comment by iHiD** [comment]
Yeah - please don't merge badge things without me agreeing to things. I'll revert and reopen for now. 

@ErikSchierboom any way to enforce this?

**Comment by kotp** [comment]
Sorry for the extra steps…

**Comment by iHiD** [comment]
Not your fault. I should have been more explicit somewhere! :)

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom any way to enforce this?

There is. First, we'd have to add you to the codeowners file. I've created https://github.com/exercism/v3/pull/1758 for that.

To force only being able to merge when you've approved, we'd have to enable the "Require review from Code Owners" rule in the branch protection settings (see [this document](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners)). Our [existing CODEOWNERS file](https://github.com/exercism/v3/blob/master/.github/CODEOWNERS) is setup such that each track PR would then have to be approved by someone from that track, which could be problematic for some tracks. We could add a rule that we two are also allowed to approve, but we'd also be notified of every single new PR.

**Comment by iHiD** [comment]
Let's just stick with codeowners and we'll go from there for now. Thanks :)

**Pull request merged**
