### PR TITLE
[Common Lisp] Add sameness Concept Exercise

### PR DESCRIPTION
**Pull request by verdammelt**
Closes https://github.com/exercism/v3/issues/1322

### CODE REVIEW

**Comment by verdammelt** [comment]
Left some parts pretty sketchy - but perhaps a place to begin with this exercise. NOTE: the example file is actually a sketch of the way to write the tests along with a possible stub to give the student.

**Comment by TheLostLambda** [comment]
I think this is a fantastic start! I'm loving the way it's looking! I think you've adapted the story to be even better and I like the testing system! It's always crazy how many things I forget exist (like destructuring in `loop`) or don't use enough (like conditions and `constantly`).

Let me know if you ever want help with this! I'm excited about it so far!

**Comment by verdammelt** [comment]
> Let me know if you ever want help with this! I'm excited about it so far!

Since the bot created this I don't think I can push changes to this
PR. So do we merge it and follow it up with changes? Or do we drop
this PR and create a cleaner one on a branch one of controls?

**Comment by TheLostLambda** [comment]
Ah, I didn't realize! Hmm, I'd be fine with either. I don't think there is any harm in merging it in as long as we don't add it to the `config.json` just yet.

I'd merge it if I could, but I think the world's most annoying markdown formatter (Prettier) won't let us. We could ask on the Slack if there is a way to push to this PR, otherwise we may actually need to remake it.

**Comment by verdammelt** [comment]
`/format`

**Comment by ynfle** [comment]
image
@SaschaMann @ErikSchierboom

**Comment by verdammelt** [comment]
@TheLostLambda due to the inability to reformat this PR I'm closing it and opening a new one #1823 . Let's take the discussion of next steps over there.

**Comment by SaschaMann** [comment]
@ErikSchierboom does the bot set the "Allow edits by maintainers" flag?

**Comment by ErikSchierboom** [comment]
@SaschaMann It doesn't do that explicitly I think. We are currently letting the dashboard user create the PR themselves, and I don't see a [query string parameter to allow edits](https://docs.github.com/en/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters#supported-query-parameters). The [PR API](https://developer.github.com/v3/pulls/#create-a-pull-request) _does_ allow us to do that, so it might be useful to create the PR on the backend instead. @iHiD what do you think?

**Comment by SaschaMann** [comment]
Ah okay. You could also run prettier on the bot branch automatically. Either via an action on the bot's fork or as part of the dashboard.

**Pull request closed without merging**
