### PR TITLE
Pin rebase action to commit hash

### PR DESCRIPTION
**Pull request by SaschaMann**
See https://github.com/exercism/v3/pull/135#issuecomment-575354375 and/or https://julienrenaux.fr/2019/12/20/github-actions-security-risk/

### CODE REVIEW

**Comment by iHiD** [comment]
Sweet. Thanks.

I'd also be a fan of forking the code into exercism's org.

**Comment by SaschaMann** [comment]
> I'd also be a fan of forking the code into exercism's org.

That would work, too, but we'd probably want to setup some kind of update reminder for them. Though in that case, I think vendoring them inside the repo itself would be best because that would be enforceable on an org-wide level through a setting: https://github.blog/2019-10-03-github-actions-adds-policy-controls-for-organization-and-repository-owners/

**Comment by iHiD** [comment]
OK. Thank makes sense. Thanks. 

(cc @ErikSchierboom and @kntsoriano into this as you'll be responsible for managing Actions on an ongoing basis)

**Comment by ErikSchierboom** [comment]
@iHiD Thanks for the heads-up!

**Pull request merged**
