### PR TITLE
[Python] Add Concepts from v2 exercise: leap

### PR DESCRIPTION
**Pull request by yawpitch**
First pass list of concepts to address #459

### CODE REVIEW

**Comment by aldraco** [comment]
Although it isn't in this implementation, many students begin the exercise using `if ... else` statements. I'd add `if ... elif ... else` to the list for that reason.

+1 to mentioning duck-typing as a separate concept.

**Comment by yawpitch** [comment]
@aldraco I'm a little hesitant to add `conditionals` as they're a bit of a red herring with `leap` (any equally performing solution using conditionals will directly reduce to the above) . In effect they're more of a prerequisite concept of Boolean logic than they are a concept necessary to this exercise.

@ErikSchierboom should we be fleshing these out with all the prerequisite concepts as well, rather than just the concepts needed to address the problem directly?

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom should we be fleshing these out with all the prerequisite concepts as well, rather than just the concepts needed to address the problem directly?

@yawpitch The focus should just be one the concepts needed to address the problem in an idiomatic way.

**Comment by yawpitch** [comment]
> > @ErikSchierboom should we be fleshing these out with all the prerequisite concepts as well, rather than just the concepts needed to address the problem directly?
> 
> @yawpitch The focus should just be one the concepts needed to address the problem in an idiomatic way.

@ErikSchierboom thanks, but that also touches on a thought [here](https://github.com/exercism/v3/pull/420#issuecomment-581353533) ... we should be re-writing our example solutions, where necessary, to reflect current idioms.

**Comment by ErikSchierboom** [comment]
> thanks, but that also touches on a thought here ... we should be re-writing our example solutions, where necessary, to reflect current idioms.

Ah, I see. I don't think I would bother too much with that, as it might be a lot of work for possibly not that much gain. But if there are Python 2 concepts involved that would no longer be used in Python 3, you could omit them or be explicit about them in the document.

**Comment by yawpitch** [comment]
> > thanks, but that also touches on a thought here ... we should be re-writing our example solutions, where necessary, to reflect current idioms.
> 
> Ah, I see. I don't think I would bother too much with that, as it might be a lot of work for possibly not that much gain. But if there are Python 2 concepts involved that would no longer be used in Python 3, you could omit them or be explicit about them in the document.

Right. The example.py in the linked issue for `phone-number` is pretty bad, compared to how you’d want to write it these days. Not so much Python2 idioms in that case as not using Python3 idioms (and also it’s just generally weak sauce). I’ll suggest adding topics for the newer idioms at least.

**Comment by ErikSchierboom** [comment]
> I’ll suggest adding topics for the newer idioms at least.

👍 As an alternative, you could also choose a different example ;)

**Comment by yawpitch** [comment]
This is my own PR, but is also in a sufficient state that I'm going to suggest we merge it into the `python-concept-references` branch for cleanup and harmonization with the other "extract" PRs.

**Pull request merged**
