### PR TITLE
Use a faster link-verifier

### PR DESCRIPTION
**Pull request by SaschaMann**
[This link verifier](https://github.com/bmuschko/link-verifier) is roughly 10x faster than the previous one. It's written in Go and available as a binary, and thus easier to run locally.

Example test builds: https://github.com/SaschaMann/v3/pull/1

### CODE REVIEW

**Comment by SaschaMann** [comment]
It would be nice if it would print a summary of failed files at the bottom instead of having to search through them. If there are any command line wizards here that know a way to do that, I'd appreciate if you added it to this PR :D

**Comment by iHiD** [comment]
I'm happy for this to be merged. Ideally it would check `_sidebar.md` files, but that might involved too much magic, so in that case it needs to skip them.

**Comment by SaschaMann** [comment]
I think it checks every *.md file.

**Comment by SaschaMann** [comment]
Did a rebase. It does seem to check `_sidebar.md` files as well. Not sure why this triggers the Julia CI workflows...

**Comment by ErikSchierboom** [comment]
There is a merge conflict.

**Comment by SaschaMann** [comment]
It doesn't find any links in the issue templates and the sidebar files, so it can't test them but it also won't fail due to them. Does that work for you?

**Comment by ErikSchierboom** [comment]
@SaschaMann I've looked into the output of the link verifier, and it looks to me like it is only checking external links:

<pre>
Verifying file: docs/maintainers/migrating-your-config-json-files.md
No links found.
</pre>

I think the main goal of the link verifier is to check the internal links. Is this something that can be configured?

**Comment by SaschaMann** [comment]
I just noticed that as well, must've missed it before. There's no config option for it unfortunately. Sorry, I should have checked that earlier.

**Comment by ErikSchierboom** [comment]
No problem. It was worth checking out, as the link verifier _is_ slow.

**Pull request closed without merging**
