### PR TITLE
[JavaScript] Improve Concept Exercise: numbers

### PR DESCRIPTION
**Pull request by aimorris**
Changes a single line in `instructions.md` to be clearer and more consistent.

### CODE REVIEW

**Comment by aimorris** [comment]
> The problem with this is that in the exercise we use `day_rate`. Now the connection between that and this line is lost.

You also use `monthRate`, but I haven't changed the line explaining how many billable days are in a month?

**Comment by SleeplessByte** [comment]
That's not a counter argument.

**Comment by aimorris** [comment]
I thought that you didn't like this change because the link between `dayRate()` and "daily rate" was lost.

But I am changing it to be consistent with the `monthRate()` which links with "a month has 22 billable days".

So either the explanation of the daily rate or the monthly rate needs to change for consistency?

**Comment by SleeplessByte** [comment]
There doesn't need to be consistency in the explanation. We're not optimising for "skim as fast as you can". It's a set of rules as part of a story.

**Comment by aimorris** [comment]
Alright,
should I close this PR?

**Pull request closed without merging**
