### PR TITLE
[C++] Extract concepts from v2 exercise: sieve

### LINKED ISSUE #600: [C++] Extract Concepts from v2 exercise: sieve
Extract the list of concepts required to solve the v2 C++ exercise: `sieve`. For each concept, describe why it is required to solve the exercise. Keep in mind that an exercise can have multiple approaches (you can find community solutions here: `https://exercism.io/tracks/cpp/exercises/sieve/solutions`). The goal of this task is to help determine the total list of concepts that make up `sieve`.

The list of concepts should be stored in the following document: `languages/cpp/reference/exercise-concepts/sieve.md`. [Use this link to create a PR to add this document][pr-link].

[pr-link]: ../new/master?filename=languages/cpp/reference/exercise-concepts/sieve.md

### PR DESCRIPTION
**Pull request by silvanocerza**
Closes #600 

The current tests for this exercise expect a `prime` function with an `int` argument and that returns a `vector<int>`, I think this could be changed to use `unsigned int` since prime numbers can only be positive. Just a personal consideration.

### CODE REVIEW

**Comment by silvanocerza** [comment]
> IMO `std::vector<bool>` should be a concept itself, since we should pretty much all do `using dynamic_bitset = std::vector<bool>;`

That seems to me like a generic programming concept though and not a C++ Concept, wouldn't it? 

If you teach what's a `vector` to a student that knows what are booleans I'd expect him/her to understand that by "combining" the two you can create a dynamic bitset.

**Comment by AeroStun** [comment]
Problem is that it's not just a combination of the two, and we must at some point warn them that in the whole STL, that specific specialization exists and has a different semantic (namely, it uses a proxy value type as its reference type)

**Comment by silvanocerza** [comment]
Maybe a `bitset` concept where we explain both?

**Comment by AlexLeSang** [comment]
When it comes to `vector<bool>`, I agree that it should be a Concept on its own. Considering how much knowledge one has to posses in order to understand how it actually works. Proxy value types and operator overload are required to understand the interfaces.

**Comment by silvanocerza** [comment]
Should I add `bitset` to the list of Concepts to get this approved?

**Comment by AlexLeSang** [comment]
> Should I add `bitset` to the list of Concepts to get this approved?

I think that `std::bitset` and `std::vector<bool>` should be added to the list of Concepts, under 'Types'. After that you can refer to in in your list of concepts.

Do you want to extend the list of Concepts?

**Comment by marvelou-s** [comment]
@silvanocerza 
IMO, there are some misundestood paragraphs:
- array/collection: the result is a resizable array - `std::array` is the container that encapsulates fixed size array and have the same semantics as the C-style array. I know that you meant `std::vector`, but it is not clear ;)
- bitset: `vector<bool>` is a dynamic bitset - Would it not be more appropriate to separate this concept for a few others?
1.  `std::vector`: sequence container that encapsulates dynamic size array
2.  `std::vector<bool>`: specialized version of `std::vector` which is optimized to store bit values

**Comment by silvanocerza** [comment]
> Do you want to extend the list of Concepts?

Yes, I'll do it.

Just to recap, I should add three new Concepts:
* std::vector
* std::vector<bool>
* std::bitset

Am I right?

**Comment by marvelou-s** [comment]
@silvanocerza, enlarge it by two new concepts:
- `std::vector`
- `std::vector<bool>`

`std:bitset` is different by comparison to `std::vector<bool>`, so we shouldn't emphasize on something what we didn't use in example solution.

**Comment by silvanocerza** [comment]
Sorry, I wasn't clear enough. I mean to add those three Concepts to the main list of Concepts, and here only `std::vector` and `std::vector<bool>`.

I'd probably replace `array/collection` with `std::vector`, does it makes sense?

**Pull request merged**
