### PR TITLE
[JavaScript] Refactor boolean exercise comments

### PR DESCRIPTION
**Pull request by peterchu999**

### CODE REVIEW

**Comment by SleeplessByte** [comment]
@peterchu999 this unfortunately also has all the `array-analysis` in here. Can you separate our the `booleans` stuff?

**Comment by peterchu999** [comment]
oke i'll figure out how

**Comment by peterchu999** [comment]
can this do @SleeplessByte ?

**Comment by SleeplessByte** [comment]
Thank you @peterchu999 !!

**Pull request merged**
